main/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from . import views
urlpatterns=[
    path('',views.home,name='home'),
    path('all-news',views.all_news,name='all-news'),
    path('detail/<int:id>',views.detail,name='detail'),
    path('all-category',views.all_category,name='all-category'),
    path('category/<int:id>',views.category,name='category'),
    path('login/', views.login_user),
    path('login/submit', views.submit_login),
    path('logout/', views.logout_user),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls')),
]

main/models.py
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField

class Category(models.Model):
    title=models.CharField(max_length=200)
    category_image=models.ImageField(upload_to='imgs/')

    class Meta:
        verbose_name_plural='Categories'

    def __str__(self):
        return self.title

# News Model
class News(models.Model):
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    title=models.CharField(max_length=300)
    image=models.ImageField(upload_to='imgs/')
    detail=models.TextField()
    add_time=models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural='News'

    def __str__(self):
        return self.title

# Comments
class Comment(models.Model):
    news=models.ForeignKey(News,on_delete=models.CASCADE)
    name=models.CharField(max_length=100)
    email=models.CharField(max_length=200)
    comment=models.TextField()
    status=models.BooleanField(default=False)

    def __str__(self):
        return self.comment

main/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate,login, logout
from django.views.decorators.csrf import csrf_protect
from django.contrib import messages
from .models import News, Category, Comment
from rest_framework import mixins, generics, viewsets
from .serializers import CategorySerializer, NewsSerializer, CommentSerializer

def home(request):
    first_news = News.objects.first()
    three_news = News.objects.all()[1:3]
    three_categories = Category.objects.all()[0:3]
    return render(request, 'home.html', {
        'first_news':first_news,
        'three_news':three_news,
        'three_categories':three_categories
    })

# All News
def all_news(request):
    all_news = News.objects.all()
    return render(request, 'all-news.html', {
        'all_news':all_news
    })

# Detail Page
def detail(request,id):
    news = News.objects.get(pk = id)
    if request.method == 'POST':
        name = request.POST['name']
        email = request.POST['email']
        comment = request.POST['message']
        Comment.objects.create(
            news = news,
            name = name,
            email = email,
            comment = comment
        )
        messages.success(request, 'Comment submitted but in moderation mode.')
    category = Category.objects.get(id = news.category.id)
    rel_news = News.objects.filter(category = category).exclude(id = id)
    comments = Comment.objects.filter(news = news, status = True).order_by('-id')
    return render(request, 'detail.html' ,{
        'news':news,
        'related_news':rel_news,
        'comments':comments
    })

# Fetch all category
def all_category(request):
    cats = Category.objects.all()
    return render(request, 'category.html', {
        'cats':cats
    })

# Fetch all category
def category(request,id):
    category = Category.objects.get(id = id)
    news = News.objects.filter(category = category)
    return render(request, 'category-news.html', {
        'all_news':news,
        'category':category
    })

# Create your views here.
class CommentList(
    mixins.ListModelMixin,
    mixins.CreateModelMixin,
    mixins.RetrieveModelMixin,
    mixins.UpdateModelMixin,
    mixins.DestroyModelMixin,
    viewsets.GenericViewSet,
):

    queryset = Comment.objects.all()
    serializer_class = CommentSerializer

class CategoryList(generics.ListAPIView):

    serializer_class = CategorySerializer
    queryset = Category.objects.all()

class NewsList(generics.ListAPIView):

    queryset = News.objects.all()
    serializer_class = NewsSerializer
    
def login_user(request):
    return render(request, 'login.html')

@csrf_protect
def submit_login(request):
    if request.POST:
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('/')
        else:
            messages.error(request, 'Usuário e senha inválidos. Tente novamente')
        return redirect('/login/')

def logout_user(request):
    logout(request)
    return redirect('/login/')

main/templates/all-news.html
{% extends 'base.html' %}
{% block content %}
<main class="container mt-3 mb-5">
	<h3 class="border-bottom pb-1 my-4">Ver sobre</h3>
    <!-- News Box -->
    {% for news in all_news %}
	<div class="card mb-4 shadow">
	  <div class="row no-gutters">
	    <div class="col-md-3">
            <img src="/media/{{news.image}}" class="card-img-top" alt="{{news.title}}">
	    </div>
	    <div class="col-md-8">
	      <div class="card-body">
	        <h5 class="card-title">{{news.title}}</h5>
	        <p class="card-text">{{news.detail}}</p>
	        <p class="card-text"><a href="/detail/{{news.id}}" class="btn btn-sm btn-primary">Ler mais</a></p>
	      </div>
	    </div>
	  </div>
    </div>
    {% endfor %}
</main>
{% endblock %}

main/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>{% block title %}Home Page{% endblock %}</title>
	<!-- Bootstrap 4 CSS -->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/bs4/bootstrap.min.css' %}" />
	<!-- Main Jquery -->
	<script type="text/javascript" src="{% static 'vendor/jquery.min.js' %}"></script>
	<!-- Bootstrap Js -->
	<script type="text/javascript" src="{% static '/vendor/bs4/bootstrap.min.js' %}"></script>
</head>
<body>
	<!-- Top News -->
	<nav class="navbar navbar-expand-lg navbar-dark bg-danger">
		<div class="container">
		  <a class="navbar-brand" href="/">The Plans</a>
		  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
		    <span class="navbar-toggler-icon"></span>
		  </button>
		  <div class="collapse navbar-collapse" id="navbarNav">
		    <ul class="navbar-nav ml-auto">
		      <li class="nav-item active">
		        <a class="nav-link" href="/">Início</a>
		      </li>
		      <li class="nav-item">
		        <a class="nav-link" href="{% url 'all-news' %}">Todas as notícias</a>
		      </li>
		      <li class="nav-item">
		        <a class="nav-link" href="{% url 'all-category' %}">Todas as categorias</a>
		      </li>
			  <li class="nav-item">
		        <a class="nav-link" href="/login">Entrar</a>
		      </li>
		    </ul>
		  </div>
	  	</div>
    </nav>
    
    {% block content %}
    {% endblock %}

<hr/>
<footer class="text-muted">
  <div class="container">
    <p class="float-right">
      <a href="#">Back to top</a>
    </p>
    <p>Projeto desenvolvido em<a href="https://github.com/bielmartin"> Django</a>, sinta-se a vontade para útilizar e aperfeiçoar!</p>
  </div>
</footer>
</body>
</html>

main/templates/category-news.html
{% extends 'base.html' %}
{% block content %}
<main class="container mt-3 mb-5">
	<h3 class="border-bottom pb-1 my-4">{{category.title}}</h3>
    <!-- News Box -->
    {% for news in all_news %}
	<div class="card mb-4 shadow">
	  <div class="row no-gutters">
	    <div class="col-md-3">
            <img src="/media/{{news.image}}" class="card-img-top" alt="{{news.title}}">
	    </div>
	    <div class="col-md-8">
	      <div class="card-body">
	        <h5 class="card-title">{{news.title}}</h5>
	        <p class="card-text">{{news.detail}}</p>
	        <p class="card-text"><a href="/detail/{{news.id}}" class="btn btn-sm btn-primary">Ler mais</a></p>
	      </div>
	    </div>
	  </div>
    </div>
    {% endfor %}
</main>
{% endblock %}

main/templates/category.html
{% extends 'base.html' %}
{% block content %}
<main class="container mt-3 mb-5">
	<h3 class="border-bottom pb-1 my-4">Todas as categorias</h3>
	<div class="row">
		<!-- Category Box -->
		{% for cat in cats %}
		<div class="col-md-4">
			<div class="card mb-3 shadow">
            <img src="/media/{{cat.category_image}}" class="card-img-top" alt="{{cat.title}}">
			  <div class="card-body">
			    <h5 class="card-title">{{cat.title}}</h5>
			    <hr/>
			    <p class="card-text"><a href="category/{{cat.id}}" class="btn btn-sm btn-primary">Ver sobre</a></p>
			  </div>
			</div>
		</div>
		{% endfor %}
	</div>
</main>
{% endblock %}

main/templates/detail.html
{% extends 'base.html' %}
{% block content %}
<main class="container mt-3 mb-5">
	<!-- featured news -->
	<div class="row my-3">
		<!-- Left -->
		<div class="col-md-8">
			<div class="card mb-3">
                <img src="/media/{{news.image}}" class="card-img-top" alt="{{news.title}}">
			  <div class="card-body">
			    <h5 class="card-title">{{news.title}}</h5>
			    <hr/>
			    <p class="card-text">{{news.detail}}</p>
			  </div>
			  <div class="card-footer">
			  	Em <a href="/category/{{news.category.id}}">{{news.category.title}}</a>
			  </div>
			</div>

			<!-- Comments -->
			<div class="card my-4">
				<h6 class="card-header">Adicionar comentário</h6>
				<div class="card-body">
					{% for message in messages %}
					<p class="text-success">{{message}}</p>
					{% endfor %}
					<form method="post" action="/detail/{{news.id}}">
						{% csrf_token %}
						<div class="form-group row">
							<label class="col-md-2">Nome<span class="text-danger">*</span></label>
							<div class="col-md-10">
								<input type="text" name="name" required class="form-control" />
							</div>
						</div>
						<div class="form-group row">
							<label class="col-md-2">Email<span class="text-danger">*</span></label>
							<div class="col-md-10">
								<input type="temailext" name="email" required class="form-control" />
							</div>
						</div>
						<div class="form-group row">
							<label class="col-md-2">Comentário<span class="text-danger">*</span></label>
							<div class="col-md-10">
								<textarea class="form-control" name="message" required></textarea>
							</div>
						</div>
						<input type="submit" class="btn btn-primary" />
					</form>
				</div>
			</div>
			<!-- Previous Comments -->
			<div class="card my-4">
				<h6 class="card-header">Comentários</h6>
				<div class="card-body">
					{% for comment in comments %}
					<blockquote class="blockquote text-right">
					  <p class="mb-0">{{comment.comment}}</p>
					  <footer class="blockquote-footer">{{comment.name}} <cite title="Source Title">{{comment.email}}</cite></footer>
					</blockquote>
					<hr/>
					{% endfor %}
				</div>
			</div>
		</div>
		<!-- Related News -->
		<div class="col-md-4">
			<h3 class="mb-3 border-bottom pb-1">Mais desta categoria</h3>
			<!-- Category Box -->
			{% for news in related_news %}
			<div class="card mb-3 shadow">
                <img src="/media/{{news.image}}" class="card-img-top" alt="{{news.title}}">
			  <div class="card-body">
			    <h5 class="card-title">{{news.title}}</h5>
			    <hr/>
			    <p class="card-text"><a href="/detail/{{news.id}}" class="btn btn-sm btn-primary">Ler mais</a></p>
			  </div>
			</div>
			{% endfor %}
		</div>
	</div>
</main>
{% endblock %}

main/templates/home.html
{% extends 'base.html' %}
{% block content %}
<main class="container mt-3 mb-5">
	<!-- featured news -->
	<div class="row my-3">
		<!-- Left -->
		<div class="col-md-7">
			<div class="card mb-3">
			  <img src="media/{{first_news.image}}" class="card-img-top" alt="{{first_news.title}}">
			  <div class="card-body">
			    <h5 class="card-title">{{first_news.title}}</h5>
			    <hr/>
			    <p class="card-text"><a href="/detail/{{first_news.id}}" class="btn btn-sm btn-primary">Ler mais</a></p>
			  </div>
			</div>
		</div>
		<!-- Right -->
		<div class="col-md-5" style="max-height: 450px; overflow: auto;">
			{% for news in three_news %}
			<!-- News Box -->
			<div class="card">
			  <div class="row no-gutters">
			    <div class="col-md-4">
					<img src="media/{{news.image}}" class="card-img-top" alt="{{news.title}}">
			    </div>
			    <div class="col-md-8">
			      <div class="card-body">
			        <h5 class="card-title">{{news.title}}</h5>
			        <p class="card-text"><a href="/detail/{{news.id}}" class="btn btn-sm btn-primary">Ler mais</a></p>
			      </div>
			    </div>
			  </div>
			</div>
			<hr/>
			{% endfor %}
		</div>
	</div>
	<!-- Category Wise News -->
	{% for category in three_categories %}
	<h3 class="border-bottom pb-1">{{category.title}} <a href="/category/{{category.id}}" class="float-right btn btn-sm btn-dark">Ver mais</a></h3>
	<div class="row my-4">
		{% for news in category.news_set.all %}
			{% if forloop.counter < 5 %}
			<!-- News box -->
			<div class="col-md-3">
				<div class="card mb-3 shadow">
				<img src="/media/{{news.image}}" class="card-img-top" alt="{{news.title}}">
				<div class="card-body">
					<h5 class="card-title">{{news.title}}</h5>
					<hr/>
					<p class="card-text"><a href="#" class="btn btn-sm btn-primary">Ler mais</a></p>
				</div>
				</div>
			</div>
			{% endif %}
		{% endfor %}
	</div>
	{% endfor %}
	<!-- End Single Category -->
</main>
{% endblock %}

main/templates/login.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Blog Template for Bootstrap</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.1/examples/blog/">

    <!-- Bootstrap core CSS -->
    <link 
    href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
    rel="stylesheet" 
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
    crossorigin="anonymous">

    <!-- Custom styles for this template -->
    <link 
    href="https://fonts.googleapis.com/css?family=Playfair+Display:700,900" 
    rel="stylesheet">
        <style type="txt/css">
            /* stylelint-disable selector-list-comma-newline-after */
            .alone{
              width: 700px;
              height: 350px;
            }

        </style>
  </head>

  <body>

    <div class="container">
      <header class="blog-header py-3">
        <div class="row flex-nowrap justify-content-between align-items-center">
          <div class="col-4 pt-1">
            <a class="text-muted" href="/">Retomar a leitura</a>
          </div>
          <div class="col-4 text-center">
            <a class="blog-header-logo text-dark" href="/">The Plans</a>
          </div>
          <div class="col-4 d-flex justify-content-end align-items-center">
            <a class="text-muted" href="/">
              <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mx-3"><circle cx="10.5" cy="10.5" r="7.5"></circle><line x1="21" y1="21" x2="15.8" y2="15.8"></line></svg>
            </a>
          </div>
        </div>
      </header>

      <div class="jumbotron p-3 p-md-5 text-white rounded bg-black alone">
        <div class="col-md-6 px-0">
            <form action="submit", method="POST">{% csrf_token %}
                <h2>Registro de Usuário</h2>
                <div class="form-group">
                    <label for="username">Usuário</label>
                    <input type="text" class="form-control" id="username" name="username"
                    placeholder="Nome de usuário">
                </div>

                <div class="form-group">
                    <label for="password">Senha</label>
                    <input type="password" class="form-control" id="password" name="password"
                    placeholder="Senha">
                </div>

                <div>
                    {% for message in messages %}
                        <div class="alert alert-danger", style="margin-top:1rem;">
                            <strong>ERROR!</strong> {{ message }}
                        </div>
                    {% endfor %}
                    <button type="submit" class="btn-secondary", style="margin-top:1rem;", href="/">Logar</button>
                </div>

            </form>
        </div>
      </div>

      <div class="row mb-2">
        <div class="col-md-6">
          <div class="card flex-md-row mb-4 shadow-sm h-md-250">
        </div>
        </div>
      </div>
    </div>

    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8 blog-main">

        </div><!-- /.blog-main -->



      </div><!-- /.row -->

    </main><!-- /.container -->

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="../../assets/js/vendor/popper.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <script src="../../assets/js/vendor/holder.min.js"></script>
    <script>
      Holder.addTheme('thumb', {
        bg: '#55595c',
        fg: '#eceeef',
        text: 'Thumbnail'
      });
    </script>
  </body>
</html>

main/templates/pdf_template.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-widtd, initial-scale=1.0">
    <title>Pdf Templates</title>

    <style>
      @page {
        size: "A4";
        margin: 2.5cm 1.5cm 3.5cm 1.5cm;

        @top-center{
          content: "COMPANY NAME";
        }
      }
    </style>
  </head>
  <body>
    <img
      src="http://yt3.ggpht.com/a-/A0h14GjwSplm_q0kuCFYI021gXv5xY1ywjtBmnNv2_slnQ=s100-c-k-c0xffffffff-no-rj-mo"
    />

    <h2>Noticia Portatil</h2>

    <div class="table">
      <tbody>
        {% for template in templates %}
        <tr>
          <td>{{forloop.counter}}</td>
          <td>{{template.tittle}}</td>
          <td>
            <figure>
              <img src="{{template.image}}" alt="Erro de carregamento na imagem">
            </figure>
          </td>
          <td>{{template.detail}}</td>
          <td>{{template.add_time}}</th>
        </tr>

        {% endfor %}

        <tr>
          <td>Total</td>
          <td>{{total}}</td>
        </tr>
      </tbody>
    </div>
  </body>
  </html>